Repository knative/ux, pull requests merged in 2024-03, with the labels that each got.

#114 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#120 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#119 Document new contributing process
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#121 Added the Introduction to the Contributor Journey Research
  user-research/contributor-research/Introduction.md
Labels: kind/documentation, size/M, lgtm, approved

#124 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
