Repository knative/ux, pull requests merged in 2024-08, with the labels that each got.

#172 Fix issue #156:Create survey questions for Eventing Onboarding Research
  user-research/eventing-onboarding-research/assets/Survey-Design.md
Labels: kind/documentation, size/S, lgtm, approved

#177 Fix bi-weekly reminder logic in GitHub Actions workflow
  .github/workflows/bi-weekly-UX-WG-meeting-reminder.yaml
Labels: lgtm, approved, size/XS

#178 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
