Repository knative/ux, pull requests merged in 2024-05, with the labels that each got.

#136 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#142 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 Knative Sample App Graphics styling
  designs/sample-app/sample1-how-to-use-kn-k8s.png
  designs/sample-app/sample2-run-nodejs.png
  designs/sample-app/sample3-trigger.png
  designs/sample-app/sample4-kamel.png
  designs/sample-app/sample5-extra-challenge.png
  designs/website/Website_V0.png
  designs/website/Website_V1.md
  designs/website/Website_V1.png
Labels: lgtm, approved, size/XS

#139 Contributor Experience Research (Spring 2024)
  user-research/contributor-research/Key-Findings.md
  user-research/contributor-research/README.md
  user-research/contributor-research/Recommendations.md
  user-research/contributor-research/assets/additional-insights.png
  user-research/contributor-research/assets/community-engagement.png
  user-research/contributor-research/assets/contributor-category-chart.png
  user-research/contributor-research/assets/contributor-challenges.png
  user-research/contributor-research/assets/duration-of-involvement-chart.png
  user-research/contributor-research/assets/education-work-chart.png
  user-research/contributor-research/assets/exp-levels-chart.png
  user-research/contributor-research/assets/maintainer-challenges.png
  user-research/contributor-research/assets/motivations.png
  user-research/contributor-research/assets/reasons-for-disengagement.png
  user-research/contributor-research/assets/recommendations.png
Labels: lgtm, approved, size/XL
